# Default, select no device
PUT {{SwitcherPi.Api_HostAddress}}/api/Devices?id=0

###

# Select device 1
PUT {{SwitcherPi.Api_HostAddress}}/api/Devices?id=1

###

# Select device 2
PUT {{SwitcherPi.Api_HostAddress}}/api/Devices?id=2

###

# Select device 3
PUT {{SwitcherPi.Api_HostAddress}}/api/Devices?id=3

###

# Get device 1 state
GET {{SwitcherPi.Api_HostAddress}}/api/Devices/1

###

# Set device 1 to selected
POST {{SwitcherPi.Api_HostAddress}}/api/Devices/1
Content-Type: application/json

{
  "isSelected": true
}

###

# Set device 1 to not selected
POST {{SwitcherPi.Api_HostAddress}}/api/Devices/1
Content-Type: application/json

{
  "isSelected": false
}