# Default, select no device
PUT {{SwitcherPi.Api_HostAddress}}/api/Devices?id=0
Accept: application/json

###

# Select device 1
PUT {{SwitcherPi.Api_HostAddress}}/api/Devices?id=1
Accept: application/json

###

# Select device 2
PUT {{SwitcherPi.Api_HostAddress}}/api/Devices?id=2
Accept: application/json

###

# Select device 3
PUT {{SwitcherPi.Api_HostAddress}}/api/Devices?id=3
Accept: application/json

###
